export const DUMMY_COLLEGES = [
  {
    id: 1,
    name: "Indian Institute of Technology Delhi",
    shortName: "IIT Delhi",
    domain: "iitd.ac.in",
    location: "New Delhi, DL",
    type: "IIT",
    color: "#f97316",
  },
  {
    id: 2,
    name: "Indian Institute of Technology Bombay",
    shortName: "IIT Bombay",
    domain: "iitb.ac.in",
    location: "Mumbai, MH",
    type: "IIT",
    color: "#3b82f6",
  },
  {
    id: 3,
    name: "Indian Institute of Technology Madras",
    shortName: "IIT Madras",
    domain: "iitm.ac.in",
    location: "Chennai, TN",
    type: "IIT",
    color: "#8b5cf6",
  },
  {
    id: 4,
    name: "Delhi Technological University",
    shortName: "DTU",
    domain: "dtu.ac.in",
    location: "New Delhi, DL",
    type: "State",
    color: "#10b981",
  },
  {
    id: 5,
    name: "Netaji Subhas University of Technology",
    shortName: "NSUT",
    domain: "nsut.ac.in",
    location: "New Delhi, DL",
    type: "State",
    color: "#ec4899",
  },
  {
    id: 6,
    name: "Jamia Millia Islamia",
    shortName: "JMI",
    domain: "jmi.ac.in",
    location: "New Delhi, DL",
    type: "Central",
    color: "#14b8a6",
  },
  {
    id: 7,
    name: "University of Delhi",
    shortName: "DU",
    domain: "du.ac.in",
    location: "New Delhi, DL",
    type: "Central",
    color: "#f59e0b",
  },
  {
    id: 8,
    name: "Vellore Institute of Technology",
    shortName: "VIT",
    domain: "vit.ac.in",
    location: "Vellore, TN",
    type: "Deemed",
    color: "#6366f1",
  },
  {
    id: 9,
    name: "Manipal Institute of Technology",
    shortName: "MIT Manipal",
    domain: "manipal.edu",
    location: "Manipal, KA",
    type: "Deemed",
    color: "#ef4444",
  },
  {
    id: 10,
    name: "National Institute of Technology Trichy",
    shortName: "NIT Trichy",
    domain: "nitt.edu",
    location: "Tiruchirappalli, TN",
    type: "NIT",
    color: "#06b6d4",
  },
];

export const YEAR_OPTIONS = [
  { value: "1", label: "1st Year" },
  { value: "2", label: "2nd Year" },
  { value: "3", label: "3rd Year" },
  { value: "4", label: "4th Year" },
  { value: "5", label: "5th Year" },
  { value: "pg1", label: "PG 1st Year" },
  { value: "pg2", label: "PG 2nd Year" },
];

export const STEPS = {
  COLLEGE_SELECT: 1,
  EMAIL_INFO: 2,
  OTP_VERIFY: 3,
  SUCCESS: 4,
};

export const STEP_META = [
  { step: 1, label: "College" },
  { step: 2, label: "Details" },
  { step: 3, label: "Verify" },
  { step: 4, label: "Done" },
];